const express = require('express')
const userRoute = express();
const usercontroller = require('../controllers/usercontroller')
const cartController = require('../controllers/cartController')
const authUser = require('../middleware/authUser')
const orderController = require('../controllers/orderController')
const couponController = require('../controllers/couponController')
userRoute.set('view engine','ejs')


userRoute.get('/',usercontroller.loadHome)
userRoute.get('/login',authUser.isLogout,usercontroller.loadLogin)
userRoute.get('/signup',authUser.isLogout,usercontroller.loadSignup)
userRoute.get('/otp',authUser.isLogout,usercontroller.loadOtp)
userRoute.post('/verifyOtp',usercontroller.verifyOtpPost)
userRoute.post('/resendOtp',authUser.isLogout,usercontroller.verifyOtpPost)
userRoute.post('/login',authUser.isLogout,usercontroller.loginPost)
userRoute.post('/signup',usercontroller.signupPost)
userRoute.get('/shop',usercontroller.loadShop)
userRoute.get('/singleShop',usercontroller.loadSingleShop)
userRoute.post('/singleShop',usercontroller.singleShopPost)  
userRoute.get('/profile',authUser.isLogin,authUser.isBlocked,usercontroller.loadProfile)
userRoute.post('/editProfile',authUser.isLogin,usercontroller.editProfile)
userRoute.post('/addAddress',authUser.isLogin,usercontroller.addAddress)
userRoute.post('/editAddress',authUser.isLogin,usercontroller.editAddress)
userRoute.post('/getCart',authUser.isLogin,authUser.isBlocked,cartController.getCart)
userRoute.get('/cart',authUser.isLogin,cartController.showCart)    
userRoute.post('/removeCart',authUser.isLogin,cartController.removeCart)
userRoute.get('/logout',authUser.isLogin,usercontroller.logout)
userRoute.post('/updateCart',authUser.isLogin,cartController.updateCart)
userRoute.get('/checkout',authUser.isLogin,orderController.loadCheckout)
userRoute.post('/checkoutForm',authUser.isLogin,orderController.checkoutPost)
userRoute.get('/success',authUser.isLogin,orderController.loadSuccess)
userRoute.get('/orderDetails',authUser.isLogin,orderController.orderDetails)
userRoute.post('/changePassword',usercontroller.changePassword)
userRoute.post('/cancelOrder',orderController.cancelOrder)
userRoute.post('/verifyPayment',orderController.verifyPayment)
userRoute.post('/applyCoupon',couponController.applyCoupon)
userRoute.post('/removeCoupon',couponController.removeCoupon)
userRoute.get('/wishlist',usercontroller.loadWishlist)
userRoute.post('/addToWishlist',usercontroller.addWishlist)
userRoute.post('/removeWishlist',usercontroller.removeWishlist)
userRoute.get('/pdfInvoice/:orderId',usercontroller.getInvoice)

module.exports = userRoute;     
